version: '3.8'
services:

  mysql:
    container_name: mysql_5
    build:
      context: ./
      dockerfile: mysql5.Dockerfile
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: l1jtw
      MYSQL_USER: l1jtw
      MYSQL_PASSWORD: l1jtw
      TZ: Asia/Shanghai
    volumes:
      - ./conf/sqls:/docker-entrypoint-initdb.d # init sql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    security_opt:
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M


  lineage:
    container_name: lineage_380
    build:
      context: ./
      dockerfile: lineage.Dockerfile
    ports:
      - "23:23"
    restart: always
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

